# /SS-0/ Meta Data : File Application

[Meta]                                                      #   File Meta Data
File = locations.ini                                            #   File Name
Desc = X,Y Locations For ADB Automations : Device & Games       #   File Description
Device = Samsung Galaxy S21+                                    #   Specified Device Application
Model = SM-G996U                                                #   Specified Device Model
Software = 59.0                                                 #   Specified Device Software Security Update
Android = 15.0                                                  #   Specified Android OS Version
Kernel = 5.4.274                                                #   Specified Android Kernel Version
Resolution = (1080, 2400)                                       #   Specified Device Screen Resolution

## /SS-1/ Device

### /SS-1.1/ Bottom Bar Navigation : Button Mode
[NavBar]                                                    #   Navigation Bar
Recent = (270, 2325)                                            #   Left Button
Home = (575, 2325)                                              #   Middle Button
Back = (850, 2325)                                              #   Right Button

### /SS-1.2/ Top Bar
[TopBar]                                                    #   Top Bar
PullDown = [{"Start": (x, 80)}, {"Finish": (x, 1000)}]          #   Open Top Bar (Combined: Quick View > Full View) (2 Panel: Open)
Swipe_Left = [{"Start": (x, y)}, {"Finish": (x, y)}]            #   Swipe Left to Next Menu (2 Panel: Notification > Controls)
Swipe_Right = [{"Start": (x,y)}, {"Finish": (x, y)}]            #   Swipe Right to Next Menu (2 Panel: Controls > Notification)

#### /SS-1.2.1/ 2 Panel : Notifications
[Notifications]                                             #   Top Bar 2 Panel : Push Notifications
Settings = (205, 2210)                                          #   Opens Notification Settings
ClearAll = (265, 2210)                                          #   Clears All Notifications
Notify1 = (283, 420)                                            #   Drop-Down Button for the First Notification
Notify2 = (283, 640)                                            #   Drop-Down Button for the Second Notification
Notify3 = (283, 860)                                            #   Drop-Down Button for the Third Notification
Notify4 = (283, 1080)                                           #   Drop-Down Button for the Fourth Notification
Notify5 = (283, 1300)                                           #   Drop-Down Button for the Fifth Notification
Notify6 = (283, 1520)                                           #   Drop-Down Button for the Sixth Notification
Notify7 = (283, 1740)                                           #   Drop-Down Button for the Seventh Notification
Notify8 = (283, 1960)                                           #   Drop-Down Button for the Eighth Notifications

#### /SS-1.2.2/ Combined : Quick View
[Quick]                                                     #   Top Bar Combined : Quick View
Settings = (945, 225)
Button1 = (115, 368)
Button2 = (285, 368)
Button3 = (450, 368)
Button4 = (625, 368)
Button5 = (795, 368)
Button6 = (965, 368)
Notify1 = ()
Notify2 = ()
Notify3 = ()
Notify4 = ()
Notify5 = ()
Notify6 = ()
Notify_Settings = (250, 2210)

### /SS-1.3/ Top Bar : Controls
[Controls]                                                  #   Android Controls (2-Panel: Options) (Combined: Full View)
Edit = (695, 225)                                               #   Edit This Menu Layout and Buttons
Power = (825, 225)                                              #   Turn Device On/Off
Settings = (970, 225)                                           #   Open Device Settings
##### /ss-1/ Order : Wf/Bt, Buttons, Sliders, Media, 4 Options
Wifi = (160, 400)
Bluetooth = (655, 400)
Button1 = ()
Button2 = ()
Button3 = ()
Button4 = ()
Button5 = ()
Button6 = ()
Button7 = ()
Button8 = ()
Slider1 = [{"Min": (x, y)}, {"Max": (x, y)}]
Slider2 = [{"Min": (x, y)}, {"Max": (x, y)}]
Media = ()
Option1 = ()
Option2 = ()
Option3 = ()
Option4 = ()

### /SS-1.4/ Home Screen Navigation
#### /SS-1.4.1/ 5x5 Navigation Layout : 
[Nav 5x5]                                                   #   Home 5x5 Layout
##### /ss-0/ Summary
Row1 = (x, 320)
Row2 = (x, 666)
Row3 = (x, 1010)
Row4 = (x, 1350)
Row5 = (x, 1680)
Column1 = (120, y)
Column2 = (350, y)
Column3 = (540, y)
Column4 = (745, y)
Column5 = (930, y)
##### /ss-1/ Row 1
app1 = (120, 320)
app2 = (350, 320)
app3 = (540, 320)
app4 = (745, 320)
app5 = (930, 320)
##### /ss-2/ Row 2
app6 = (120, 666)
app7 = (350, 666)
app8 = (540, 666)
app9 = (745, 666)
app10 = (930, 666)
##### /ss-3/ Row 3
app11 = (120, 1010)
app12 = (350, 1010)
app13 = (540, 1010)
app14 = (745, 1010)
app15 = (930, 1010)
##### /ss-4/ Row 4
app16 = (120, 1350)
app17 = (350, 1350)
app18 = (540, 1350)
app19 = (745, 1350)
app20 = (930, 1350)
##### /ss-5/ Row 5
app21 = (120, 1680)
app22 = (350, 1680)
app23 = (540, 1680)
app24 = (745, 1680)
app25 = (930, 1680)

### /SS-1.5/ App Drawer Layout
#### /SS-1.5.1/ 
[AppNav 5x5]                                                #   App 5x5 Layout
##### /ss-0/ Summary
Row1 = (x, )
Row2 = (x, )
Row3 = (x, )
Row4 = (x, )
Row5 = (x, )
Column1 = (, y)
Column2 = (, y)
Column3 = (, y)
Column4 = (, y)
Column5 = (, y)
##### /ss-1/ Row 1
app1 = ()
app2 = ()
app3 = ()
app4 = ()
app5 = ()
##### /ss-2/ Row2
app6 = ()
app7 = ()
app8 = ()
app9 = ()
app10 = ()
##### /ss-3/ Row3
app11 = ()
app12 = ()
app13 = ()
app14 = ()
app15 = ()
##### /ss-4/ Row4
app16 = ()
app17 = ()
app18 = ()
app19 = ()
app20 = ()
##### /ss-5/ Row5
app21 = ()
app22 = ()
app23 = ()
app24 = ()
app25 = ()

## /SS-2/ Orna Locations

### /SS-2.1/ Main Screen
[Main]                                                      #   Orna Main Screen
Allies = (75, 170)
Build = (75, 500)
Chat = (75, 260)
Codex = (320, 2250)
Explore = (975, 2150)
Inbox = (75, 390)
Items = (760, 2250)
Kingdom = (100, 2150)
Menu = (540, 2250)
Map_Options = (975, 2300)
OriginTown = (75, 630)                                          #   !OR! Event if in OriginTown

### /SS-2.2/ Kingdom Screen
[Kingdom]
Hall = (75, 290)
War = (230, 290)
Raids = (390, 290)
Gauntlet = (540, 290)
Quests = (695, 290)
Research = (855, 290)
Options = (1000, 290)

#### /SS-2.2.1/ Kingdom : Hall Tab
[Hall]
Roster = (850, 2250)

#### /SS-2.2.2/ Kingdom : War Tab
[War]
Attack = (335, 1280)
Defense = (740, 1280)
Begin= (545, 1260)

#### /SS-2.2.3/ Kingdom : Raid Tab
[Raid]
Begin = (565, 785)

#### /SS-2.2.4/ Kingdom :
[Gauntlet]

#### /SS-2.2.4/ Kingdom :
[Quests]

#### /SS-2.2.4/ Kingdom :
[Research]

#### /SS-2.2.4/ Kingdom :
[Options]


[Codex]


[Menu]


[Items]


[Explore]


[Options]

# // Attack Screen
    [Attacking]
    Attack = (800, 1885)
    Primary = (300, 1885)
    Secondary = (300, 2060)
    Spell = (800, 2060)
    Flee = (300, 2250)
    Item = (800, 2250)
    Quick.1 = (915, 1710)
    Quick.2 = (675, 1710)
    Quick.3 = (425, 1710)
    Quick.4 = (150, 1710)
    Codex = ()
    Chat = ()
    Options = ()

        [Options]
        Overview = ()
        Log = ()
        Options = ()

            [Options]
            Animation.On = ()
            Animation.Faster = ()
            Animation.Off = ()
            Effects = ()
            Caster = ()
            Status.Condense = ()
            dismantle.quality = ()
            broken = ()
            poor = ()
            standard = ()
            Superior = ()

# // Shops
    [Shop]

    [Blacksmith]

    []

    [Prompts]
    Continue.bottom = (550, 2265)
    Continue.top = ()
    
    
    
    
    
    
    
    
    
    
    
    
    [Prompts]
    Continue_bottom = (575, 2275)
    Continue_mid = (550, 1500)
    Playing_safe = (80, 1245)
    X = (550, 2300)

    [Menu]
    # // Wheel Select
    Status = (550, 500)
    Class = (550, 1165)
    Party = (815, 610)
    Apperance = (815, 1070)
    Equipment = (930, 370)
    Spells = (150, 370)
    Achievements = (280, 600)
    Quests = (280, 1070)
    # // Under-Wheel 
    MainMenu = (250, 1475)
    Options = (530, 1475)
    Help = (830, 1475)
    # // Tabs
    Status_Tab = (90, 275)
    Inventory = (270, 275)
    Runeshop = (450, 275)
    ArchPaths = (630, 275)
    Arena = (810, 275)
    Dungeon = (990, 275)
    Inbox = (970, 150)

    [Attack]
    Main = (300, 1875)
    Secondary = (300, 2075)
    Flee = (300, 2250)
    Basic = (800, 1875)
    Spells = (800, 2075)
    Items = (800, 2250)

    [Spells]
    Sp1 = (300, 1480)
    sp2 = (800, 1480)
    sp3 = (300, 1630)
    sp4 = (800, 1630)
    sp5 = (300, 1780)
    sp6 = (800, 1780)
    sp7 = (300, 1930)
    sp8 = (800, 1930)
    sp9 = (300, 2080)
    sp10 = (800, 2080)

    [Items]
    It1 = (300, 300)
    It2 = (800, 300)
    It3 = (300, 450)
    It4 = (800, 450)
    It5 = (300, 600)
    It6 = (800, 600)
    It7 = (300, 750)
    It8 = (800, 750)
    It9 = (300, 900)
    It10 = (800, 900)